import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/widgets/footer";
import Header from "@/widgets/header";

const inter = Inter({
  subsets: ["cyrillic", "latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body suppressHydrationWarning>
        <div className="bg-grid"></div>
        <Header />
        <main className="container page">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
