import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/widgets/footer";
import Header from "@/widgets/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body suppressHydrationWarning>
        <div className="bg-grid"></div>
        <Header />
        <main className="container page">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
